config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'newViewOnlySession' => 'sessions#newViewOnlySession'

  root 'static_pages#home'

  resources :repairs do
    member do
      put 'change_status'
    end
    collection do
      get 'unlock_new'
      post 'unlock_new'
      get 'active'
      get 'inactive'
    end
  end
  post 'newViewOnlyRepairForm' => 'repairs#newViewOnlyRepairForm'

  resources :users do
    member do
      get 'admin_edit_employee'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	before_save {self.email = email.downcase}

	validates :first_name, presence: true, length: { maximum: 35 }
	validates :last_name, presence: true, length: { maximum: 35 }
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
	validates :username, presence: true, length: { maximum: 35 }, uniqueness: { case_sensitive: false}
	validates :website_code, presence: true, length: { maximum: 35 }, uniqueness: true, confirmation: true, on: :create
	validates :website_code, length: { maximum: 35 }, uniqueness: true, on: :update, allow_blank: true
	has_secure_password
    validates :password, presence: true, length: { minimum: 5 }, confirmation: true, on: :create
		validates :password, length: { minimum: 5 }, confirmation: true, on: :update, allow_blank: true

	enum role: [ :Admin, :Employee, :Top_Admin ]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :login_required
before_filter :admin_approval, :only => [:new, :create, :admin_edit_employee]
before_filter :redirectForViewOnlyAccount, only: [:update, :destroy]

def index
	@users = User.all
end

def new
	@user = User.new
end

def create
	@user = User.new(user_params)
	if @user.save
			redirect_to users_path
		else 
			render 'new'
	end
end

def edit
	if User.exists?(params[:id]) && current_user.id == User.find(params[:id]).id
		@user = User.find(params[:id])
	else
		redirect_to users_path
	end
end

def admin_edit_employee
	if User.exists?(params[:id])
		@user = User.find(params[:id])
		if current_user.role == "Top_Admin"
			@user
		elsif @user.role == "Admin" || @user.role == "Top_Admin"
			redirect_to users_path
		else
			@user
		end
	else
		# flash: user does not exist
		redirect_to users_path
	end
end

def update
	@user = User.find(params[:id])
	if !params[:current_password].nil? && !params[:current_password].empty? 
		if User.find(params[:id]).authenticate(params[:current_password])
			if @user.update(user_params)
				redirect_to users_path
			else
				render 'edit'
			end
		else
			@user.errors.add(:current_password_incorrect, "")
			render 'edit'
		end
	else
		if @user.id != current_user.id && admin_logged_in?
			if @user.update(user_params)
				redirect_to users_path
			else
				render 'admin_edit_employee'
			end
		else
			if @user.update(user_params_no_passwords_or_email_or_role)
				redirect_to users_path
			else
				render 'edit'
			end
		end
	end
end

def destroy
	@user = User.find(params[:id])
	@user.destroy
	# flash: user deleted
	redirect_to users_path
end

private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :role, :email, :username, :website_code, :password, :password_confirmation, :current_password, :admin_edit )
	end

	def user_params_no_passwords_or_email_or_role
		params.require(:user).permit(:first_name, :last_name, :username, :admin_edit )
	end

	def login_required
		redirect_to login_path unless logged_in?
	end

	def admin_approval
		redirect_to users_path unless admin_logged_in?
	end

end

app/helpers/users_helper.rb
module UsersHelper
	def admin_logged_in?
		current_user.role == "Admin" || current_user.role == "Top_Admin"
	end

  def viewOnlyAccount?
    logged_in? && current_user.username.downcase.include?("viewonly")
  end
end

app/views/users/admin_edit_employee.html.erb
<%= link_to "Cancel", users_path, class: "btn btn-warning" %>
<%= link_to 'Delete User', user_path(@user), method: :delete, 
              data: {confirm: 'Are you sure you want to delete this user? This can not be undone and the data can not be retrieved.'}, class: "btn btn-danger pull-right" %>

<br>
<br>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages_user' %>

  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name , class: 'form-control' %><br>

  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name , class: 'form-control' %><br>

  <%= f.label :username, "Username" %>
  <%= f.text_field :username , class: 'form-control' %><br>

  <%= f.label :role, "Role" %>
  <% if current_user.role == "Top_Admin" %>
    <%= f.select :role, options_for_select(['Admin', 'Employee', 'Top_Admin'], @user.role), class: 'form-control' %><br>
  <% else %>
    <%= f.select :role, options_for_select(['Admin', 'Employee'], @user.role), class: 'form-control' %><br>
  <% end %>

  <%= f.label :email, "Email" %>
  <%= f.email_field :email, class: 'form-control' %><br>

  <%= f.label :website_code, "New Website Code" %>
  <br>
  <small>(Code used to unlock repair request form.)</small>
  <small><b>(Do not make this the same as the account password.)</b></small>
  <br>
  <%= f.password_field :website_code , class: 'form-control' %><br>

  <%= f.label :password, "New Account Password" %>
  <%= f.password_field :password , class: 'form-control' %><br>

  <%= f.label :password_confirmation, "Confirm Account Password" %>
  <%= f.password_field :password_confirmation , class: 'form-control' %><br>

  <%= f.submit "Save settings", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<%= link_to "Cancel", users_path, class: "btn btn-warning" %>

<br>
<br>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages_user' %>

  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name , class: 'form-control' %><br>

  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name , class: 'form-control' %><br>

  <%= f.label :username, "Username" %>
  <%= f.text_field :username , class: 'form-control' %><br>

  
  <strong>Current password required in order to change settings below</strong><br>
  <%= label :current_password, "Current Account Password" %>
  <%= password_field_tag :current_password, params[:current_password], placeholder: "Old Account Password", class: 'form-control' %><br>  

  <%= f.label :role, "Role" %>
  <% if current_user.role == "Top_Admin" %>
    <%= f.select :role, options_for_select(['Admin', 'Employee', 'Top_Admin'], @user.role), class: 'form-control' %><br>
  <% elsif current_user.role == "Admin" %>
    <%= f.select :role, options_for_select(['Admin', 'Employee'], @user.role), class: 'form-control' %><br>
  <% else %>
    <%= f.select :role, options_for_select(['Employee'], @user.role), class: 'form-control' %><br>
  <% end %>

  <%= f.label :email, "Email" %>
  <%= f.email_field :email, class: 'form-control' %><br>

  <%= f.label :website_code, "New Website Code" %>
  <br>
  <small>(Code used to unlock repair request form.)</small>
  <small><b>(Do not make this the same as the account password.)</b></small>
  <br>
  <%= f.password_field :website_code , class: 'form-control' %><br>

  <%= f.label :password, "New Account Password" %>
  <%= f.password_field :password , class: 'form-control' %><br>

  <%= f.label :password_confirmation, "Confirm Account Password" %>
  <%= f.password_field :password_confirmation , class: 'form-control' %><br>

  <%= f.submit "Save settings", class: "btn btn-primary", disabled: viewOnlyAccount? %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to	"Edit My Settings", edit_user_path(current_user), class: "btn btn-default" %>

<% if admin_logged_in? %>
	<%= link_to	"Create New User", new_user_path, class: "btn btn-default" %>
<% end %>

<br>
<br>

<div class="panel panel-default">
	<div class="panel-heading"><strong>Admin</strong></div>
	<table class="table table-hover">
			<th>Name</th>
			<th>Email</th>
			<th>Username</th>
		<% @users.where(:role => [0, 2]).each do |user| %>
			<% if current_user.role == "Top_Admin" && user.role == "Admin" %>
				<tr data-link="<%= admin_edit_employee_user_path(user) %>">
			<% else %>
				<tr>
			<% end %>
				<td> <%= user.first_name %> <%= user.last_name %></td>
				<td> <%= user.email %> </td>
				<td> <%= user.username %> </td>
			</tr>
		<% end %>
	</table>
</div>

<div class="panel panel-default">
	<% if admin_logged_in? %>
		<div class="panel-heading"><strong>Employees</strong> (click on row to edit employee settings)</div>
	<% else %>
		<div class="panel-heading"><strong>Employees</strong></div>
	<% end %>
	<table class="table table-hover">
			<th>Name</th>
			<th>Email</th>
			<th>Username</th>
		<% @users.where(:role => 1).each do |user| %>
			<% if admin_logged_in? %>
				<tr data-link="<%= admin_edit_employee_user_path(user) %>">
			<% else %>
				<tr>
			<% end %>
				<td> <%= user.first_name %> <%= user.last_name %></td>
				<td> <%= user.email %> </td>
				<td> <%= user.username %> </td>
			</tr>
		<% end %>
	</table>
</div>

app/views/users/new.html.erb
<%= link_to "Cancel", users_path, class: "btn btn-warning" %>

<br>
<br>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages_user' %>

  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name , class: 'form-control' %><br>

  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name , class: 'form-control' %><br>

  <%= f.label :role, "Role" %>
  <% if current_user.role == "Top_Admin" %>
    <%= f.select :role, options_for_select(['Admin', 'Employee', 'Top_Admin'], @user.role), class: 'form-control' %><br>
  <% else %>
    <%= f.select :role, options_for_select(['Admin', 'Employee'], @user.role), class: 'form-control' %><br>
  <% end %>

  <%= f.label :email, "Email" %>
  <%= f.email_field :email, class: 'form-control' %><br>

  <%= f.label :username, "Username" %>
  <%= f.text_field :username , class: 'form-control' %><br>

  <%= f.label :website_code, "Website Code" %>
  <br>
  <small>(Code used to unlock repair request form.)</small>
  <small><b>(Do not make this the same as the account password.)</b></small>
  <br>
  <%= f.password_field :website_code , class: 'form-control' %><br>

  <%= f.label :password, "Account Password" %>
  <%= f.password_field :password , class: 'form-control' %><br>

  <%= f.label :password_confirmation, "Confirm Account Password" %>
  <%= f.password_field :password_confirmation , class: 'form-control' %><br>

  <%= f.submit "Create new user", class: "btn btn-primary" %>
<% end %>