config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'newViewOnlySession' => 'sessions#newViewOnlySession'

  root 'static_pages#home'

  resources :repairs do
    member do
      put 'change_status'
    end
    collection do
      get 'unlock_new'
      post 'unlock_new'
      get 'active'
      get 'inactive'
    end
  end
  post 'newViewOnlyRepairForm' => 'repairs#newViewOnlyRepairForm'

  resources :users do
    member do
      get 'admin_edit_employee'
    end
  end

end

app/models/repair.rb
class Repair < ActiveRecord::Base

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	VALID_PHONE_NUMBER_REGEX = /\A[\d]{3}+\-[\d]{3}+\-[\d]{4}\z/

	validates :customer_first_name, presence: true, length: { maximum: 35 }
	validates :customer_last_name, 	presence: true, length: { maximum: 35 }
	validates :customer_id_number, length: { maximum: 20 }, numericality: true, allow_blank: true
  validates :device_description, presence: true
	validates :customer_email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, presence: true, :unless => :customer_phone_number? 
  validates :customer_phone_number, format: { with: VALID_PHONE_NUMBER_REGEX }, presence: true, :unless => :customer_email?
	validates :device_password, confirmation: true
	validates :device_problem_description, presence: true
  validates :services_fee, presence: true, :numericality => {:greater_than_or_equal_to => 0, :less_than => 1000000}
  validates :parts_fee, presence: true, :numericality => {:greater_than_or_equal_to => 0, :less_than => 1000000}

	enum status: [ :active, :ready_for_pickup, :inactive ]

	def self.search(search, option)
	  query = "%#{search}%"
	  choice = "%#{option}"
	  case option
	  when "First Name"
	  	self.where("customer_first_name ILIKE ?", query)
	  when "Last Name"
	  	self.where("customer_last_name ILIKE ?", query)
	  when "ID Number"
	  	self.where("customer_id_number ILIKE ?", query)
	  when "Email"
	  	self.where("customer_email ILIKE ?", query)
	  when "Phone Number"
	  	self.where("customer_phone_number ILIKE ?", query)
	  when "Device Description"
	  	self.where("device_description ILIKE ?", query)
	  when "Problem Description"
	  	self.where("device_problem_description ILIKE ?", query)
	  when "Serial Number"
	  	self.where("device_serial_number ILIKE ?", query)
	  when "Accessories"
	  	self.where("accessories_description ILIKE ?", query)
	  when "Repair Description"
	  	self.where("repair_description ILIKE ?", query)
	  when "Technician"
	  	self.where("technician ILIKE ?", query)
	  when "Sales Associate"
	  	self.where("sales_associate ILIKE ?", query)
	  else 
		  if search
		    self.where("customer_first_name ILIKE ? or customer_last_name ILIKE ? or customer_id_number ILIKE ?  or customer_email ILIKE ? or customer_phone_number ILIKE ? or device_description ILIKE ? or device_problem_description ILIKE ? or device_serial_number ILIKE ? or accessories_description ILIKE ? or repair_description ILIKE ? or technician ILIKE ? or sales_associate ILIKE ?", query, query, query, query, query, query, query, query, query, query, query, query)
		  else
		    self.all
		  end
		end
	end

end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
	before_filter :login_required, :except => [:new, :create, :unlock_new, :unlock_new_form, :newViewOnlyRepairForm]
	before_filter :redirectForViewOnlyAccount, only: [:update, :destroy, :change_status]
	skip_before_filter :delete_unlock_new_session_name, :only => [:new]

	def index
		redirect_to active_repairs_path
	end

	def active
		@repairs = Repair.all.where(:status => [0, 1]).search(params[:search], params[:option]).order("created_at ASC") # 0 is "active", 1 is "ready_for_pickup"
	end

	def inactive
		@repairs = Repair.all.where(status: 2).search(params[:search], params[:option]).order("created_at DESC") # 2 is "inactive"
	end

	def show
		@repair = Repair.find(params[:id])

		respond_to do |format|
			format.html
			format.pdf do
				pdf = RepairPdf.new(@repair)
				send_data pdf.render, filename: "repair-ID##{@repair.id}-#{@repair.customer_first_name}_#{@repair.customer_last_name}.pdf", type: 'application/pdf'
			end
		end
	end

	def new
		if session[:unlock_new_repair_employee_name]
			@repair = Repair.new
		else
			redirect_to unlock_new_repairs_path
		end
	end
	
	def unlock_new
		if request.post?
			employee_unlock_code = params[:employee_unlock_code]
			@user = User.find_by(website_code: employee_unlock_code)
			if @user
				session[:unlock_new_repair_employee_name] = @user.first_name + " " + @user.last_name
				session[:view_only_mode] = false
				redirect_to new_repair_path
			else
				flash[:error] = "Incorrect Employee Unlock Code"
				render unlock_new_repairs_path
			end
		end
	end

	def newViewOnlyRepairForm
		user = User.find_by(username: "ExampleViewOnlyAccount")
		employee_unlock_code = user.website_code if user
		if employee_unlock_code
			session[:unlock_new_repair_employee_name] = user.first_name + " " + user.last_name
			session[:view_only_mode] = true
			redirect_to new_repair_path
		else
			flash[:error] = "Repair Request View Only Form Not Available"
			render unlock_new_repairs_path
		end
	end

	def create
		@repair = Repair.new(repair_params)
		if @repair.save && !session[:view_only_mode]
			flash[:success] = "Thank you for submitting your repair request."
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@repair = Repair.find(params[:id])
	end

	def update
		@repair = Repair.find(params[:id])
		if @repair.update(repair_params)
			redirect_to @repair
		else
			render 'edit'
		end
	end

	def destroy
		@repair = Repair.find(params[:id])
		@repair.destroy
		redirect_to repairs_path
	end

	def change_status
		@repair = Repair.find(params[:id])
		@repair.update_attribute(:status, params[:state])
		redirect_to repairs_path
	end

	private
		def repair_params
			params.require(:repair).permit(:customer_first_name, :customer_last_name,
										   :customer_id_number, :customer_email, :customer_phone_number,
										   :device_description, :device_password, :device_serial_number,
										   :accessories_description, :device_problem_description,
										   :repair_description, :services_fee,
										   :parts_fee, :state, :device_password_confirmation,
										   :sales_associate, :technician, :dropoff_signature_data,
										   :pickup_signature_data )
		end

		def login_required
			redirect_to login_path unless logged_in?
		end
end

app/views/repairs/_repair_info.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Customer</h4></div>
      <div class="panel-body">  
        <div class="list-group" style="display: inline-block;">
          <h5 class="list-group-item-heading"> <b>Name:</b></h5>
          <p class="list-group-item-text"> <%= @repair.customer_first_name %> <%= @repair.customer_last_name %> </p>
          <h5 class="list-group-item-heading"> <b>Student ID/Perm #:</b> </h5>
          <p class="list-group-item-text"> <%= @repair.customer_id_number %> </p>
          <h5 class="list-group-item-heading"><b>Email:</b></h5>
          <p class="list-group-item-text"> <%= @repair.customer_email %> </p>
          <h5 class="list-group-item-heading"><b>Phone #:</b></h5>
          <p class="list-group-item-text"> <%= @repair.customer_phone_number %> </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Device</h4></div>
      <div class="panel-body"> 
        <div class="list-group" style="display: inline-block;">
          <h5 class="list-group-item-heading"> <b>Description:</b></h5>
          <p class="list-group-item-text"> <%= @repair.device_description %> </p>
          <h5 class="list-group-item-heading"> <b>Password:</b> </h5>
          <p class="list-group-item-text"> 
            <% if @repair.device_password.empty? %>
              No Password
            <% else%>
              <pre><%= @repair.device_password %></pre> 
            <% end %>
          </p>
          <h5 class="list-group-item-heading"><b>Serial #:</b></h5>
          <p class="list-group-item-text"> <%= @repair.device_serial_number %> </p>
          <h5 class="list-group-item-heading"><b>Accessories:</b></h5>
          <p class="list-group-item-text"> <%= @repair.accessories_description %> </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Problem Description</h4></div>
      <div class="panel-body">
        <%= @repair.device_problem_description %>
      </div>
    </div>
  </div>

</div>

app/views/repairs/active.html.erb
<ul class="nav nav-tabs">
	<li class="active"> <%= link_to 'Active', active_repairs_path %> </li>
	<li> <%= link_to 'Inactive', inactive_repairs_path%> </li>
</ul>

<br>

<%= form_for active_repairs_path, method: :get do |f| %>
	<div class="row">
		<div class="col-xs-11 col-sm-5 col-md-5">
	    <%= text_field_tag :search, params[:search], class: "form-control" %>
	  </div>
	  <div class="col-xs-3 col-sm-1 col-md-1">
			Find by
		</div>
		<div class="col-xs-4 col-sm-2 col-md-2">
	  	<%= select_tag :option, options_for_select(['First Name', 'Last Name', 'ID Number', 'Email', 'Phone Number', 'Device Description', 'Problem Description', 'Serial Number', 'Accessories', 'Repair Description', 'Technician', 'Sales Associate']), :include_blank => true, class: "form-control" %>
	  </div>

	  <div class="col-xs-12 col-sm-3 col-md-3">
	    <%= submit_tag "Search", :name => nil, class: "btn btn-primary"  %>
	  </div>
	</div>  
<% end %>

<br>

<div class="panel panel-success">
	<div class="panel-heading"><strong>Ready for pickup</strong></div>
	<table class="table table-hover">
			<th>ID</th>
			<th>Name</th>
			<th>Date Submitted</th>
		<% @repairs.where(:status => 1).each do |repair| %>
			<tr data-link="<%= repair_path(repair) %>">
				<td> <%= repair.id %>	</td>
				<td> <%= repair.customer_first_name %> <%= repair.customer_last_name %></td>
				<td> <%= repair.created_at.strftime("%x %I:%M %p") %> </td>
			</tr>
		<% end %>
	</table>
</div>

<hr>

<div class="panel panel-danger">
	<div class="panel-heading"><strong>Active</strong></div>
	<table class="table table-hover">
			<th>ID</th>
			<th>Name</th>
			<th>Date Submitted</th>
			<th>Problem</th>
			<th>Device</th>
		<% @repairs.where(:status => 0).each do |repair| %>
				<tr data-link="<%= repair_path(repair) %>">
					<td> <%= repair.id %>	</td>
					<td> <%= repair.customer_first_name %> <%= repair.customer_last_name %> </td>
					<td> <%= repair.created_at.strftime("%x %I:%M %p") %> </td>
					<td> <%= if repair.device_problem_description.length < 150
									   repair.device_problem_description
									 else 
									   repair.device_problem_description[0..150] + "..."
									 end %> 
					</td>
					<td> <%= if repair.device_description.length < 100
									  repair.device_description
									else 
									 repair.device_description[0..100] + "..."
									end %> 
					</td>
				</tr>
			<% end %>
	</table>
</div>

<% javascript_include_tag "repairs_active_inactive" %>

app/views/repairs/edit.html.erb
<h2>Edit Repair</h2>

<h3>Repair Id: <%= @repair.id %></h3>

<p>
  <%= link_to 'Cancel Edit', repair_path, class: "btn btn-warning" %>
</p>

<hr>

<h4> Sales Associate: <%= @repair.sales_associate %> </h4>

<%= render 'repair_info' %>

<button id= "more_details_button" type="button" class="btn btn-default">Edit details</button>

<hr>

<%= form_for :repair, url: repair_path(@repair), method: :patch do |f| %>
  
  <%= render 'shared/error_messages_repair' %>

  <div id="more_details" class="row" style="display: none;">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= f.label :sales_associate, "Sales Associate" %> 
        <br>
        <%= f.text_field :sales_associate, :size=>"20" %>  
      </div>
    </div>
    
    <br>

    <div class="col-xs-12 col-sm-6 col-md-3">
      <p>
      <%= f.label :customer_first_name, "First Name" %> 
      <br>
      <%= f.text_field :customer_first_name, :size=>"20" %>
      </p>
      <p>
        <%= f.label :customer_last_name, "Last Name" %>
        <br>
        <%= f.text_field :customer_last_name, :size=>"20" %>
      </p>
     
      <p>
        <%= f.label :customer_id_number, "UCSB Perm/ID #" %>
        <br>
        <%= f.text_field :customer_id_number, :size=>"7" %>
      </p>

      <p>
        <%= f.label :customer_email, "Email" %>
        <br>
        <%= f.email_field :customer_email, :size=>"25" %>
      </p>  

      <p>
        <%= f.label :customer_phone_number, "Phone Number" %>
        <br>  
        <small>(Format: 555-555-5555)</small>
        <br>
        <%= f.text_field :customer_phone_number, :size=>"14" %>
      </p>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-3">
      <p>
      <%= f.label :device_description, "Device Description" %> 
      <br>
      <%= f.text_area :device_description, :cols=> "30", :rows=>"2"  %>
      </p>
      
      <p>
        <%= f.label :device_password, "Device Password" %>
        <br>
        <%= f.text_field :device_password, :size=>"20" %>
      </p>

      <p>
        <%= f.label :device_serial_number, "Device Serial Number" %>
        <br>
        <%= f.text_field :device_serial_number, :size=>"20" %>
      </p>

      <p>
        <%= f.label :accessories_description, "Accessories" %>
        <br>
        <%= f.text_area :accessories_description, :size=>"30" %>
      </p>
    </div>

    <div class="col-xs-12 col-sm-8 col-md-3">
      <%= f.label :device_problem_description, "Problem Description" %>
      <br>
      <%= f.text_area :device_problem_description, :cols=>"60", :rows=>"4" %>
    </div>
  </div>
  
  <br>

  <p>
    <%= f.label :technician, "Technician" %>
    <br>
    <%= f.text_field :technician, :size => "20" %>
  </p>

  <p>
    <%= f.label :repair_description, "Repair Description" %>
    <br>
    <small>(What was fixed, what methods were done to fix the problems, what other problems were there, 
      <br>what replacement parts were necessary, how much the replacement parts cost, etc.)</small>
    <br>
    <%= f.text_area :repair_description, :cols=>"100", :rows=>"8" %>
  </p>

  <p>
    <%= f.label :services_fee, "Services Fee" %>
    <br>
    <%= f.number_field :services_fee, :value => number_with_precision(@repair.services_fee, :precision => 2), :step => 0.01 %>
  </p>
  
  <p>
    <%= f.label :parts_fee, "Parts Fee" %>
    <br>
    <%= f.number_field :parts_fee, :value => number_with_precision(@repair.parts_fee, :precision => 2), :step => 0.01 %>
  </p>

  <p>
    <%= f.submit "Save Repair", class: "btn btn-primary", disabled: viewOnlyAccount? %>
  </p>

<% end %>

<br>
<br>
<br>
<br>
<button id= "show_delete_button" type="button" class="btn btn-default pull-right">Show Delete Button</button>
<div id="delete_button_container" style="display: none;">
  <%= link_to 'Delete Repair', repair_path(@repair), method: :delete, 
              data: {confirm: 'Are you sure you want to delete this repair? This can not be undone and the data can not be retrieved.'}, class: "btn btn-danger", disabled: viewOnlyAccount? %>
</div>


<%= javascript_include_tag "repairs_edit" %>

app/views/repairs/inactive.html.erb
<ul class="nav nav-tabs">
	<li> <%= link_to 'Active', active_repairs_path %> </li>
	<li class="active"> <%= link_to 'Inactive', inactive_repairs_path%> </li>
</ul>

<br>

<%= form_for inactive_repairs_path, method: :get do |f| %>
	<div class="row">
		<div class="col-xs-11 col-sm-5 col-md-5">
	    <%= text_field_tag :search, params[:search], class: "form-control" %>
	  </div>
	  <div class="col-xs-3 col-sm-2 col-md-1">
			Find by
		</div>
		<div class="col-xs-4 col-sm-2 col-md-2">
	  	<%= select_tag :option, options_for_select(['First Name', 'Last Name', 'ID Number', 'Email', 'Phone Number', 'Device Description', 'Problem Description', 'Serial Number', 'Accessories', 'Repair Description', 'Technician', 'Sales Associate']), :include_blank => true, class: "form-control" %>
	  </div>

	  <div class="col-xs-12 col-sm-3 col-md-3">
	    <%= submit_tag "Search", :name => nil, class: "btn btn-primary"  %>
	  </div>
	</div>  
<% end %>

<br>

<div class="panel panel-info">
	<div class="panel-heading"><strong>Inactive</strong></div>
	<table class="table table-hover">
			<th>ID</th>
			<th>Name</th>
			<th>Date Submitted</th>
			<th>Problem</th>
			<th>Device</th>
		<% @repairs.each do |repair| %>
				<tr data-link="<%= repair_path(repair) %>">
					<td> <%= repair.id %>	</td>
					<td> <%= repair.customer_first_name %> <%= repair.customer_last_name %> </td>
					<td> <%= repair.created_at.strftime("%x %I:%M %p") %> </td>
					<td> <%= if repair.device_problem_description.length < 150
									   repair.device_problem_description
									 else 
									   repair.device_problem_description[0..150] + "..."
									 end %>
					<td> <%= repair.device_description[0..50] %> </td>
				</tr>
			<% end %>
	</table>
</div>

<% javascript_include_tag "repairs_active_inactive" %>

app/views/repairs/show.html.erb
<% if @repair.status == 'active' %>
	<% state = 0 %>
<% elsif @repair.status == 'ready_for_pickup' %>
	<% state = 1 %>
<% else %>
	<% state = 2 %>
<% end %>

<% if state == 0 or state == 1 %>
	<ul class="nav nav-tabs">
		<li class="active"> <%= link_to 'Active', active_repairs_path %> </li>
		<li> <%= link_to 'Inactive', inactive_repairs_path%> </li>
	</ul>
<% else %>
	<ul class="nav nav-tabs">
		<li> <%= link_to 'Active', active_repairs_path %> </li>
		<li class="active"> <%= link_to 'Inactive', inactive_repairs_path%> </li>
	</ul>
<% end %>

<br>
<br>

<% if state == 0 %>
	<div class="panel panel-danger">
	<div class="panel-heading"> 
		<h4>
			Repair ID: <%= @repair.id %> Active
		</h4>
	</div>
	</div>	
<% elsif state == 1 %>
	<div class="panel panel-success">
	<div class="panel-heading"> 
		<h4>
			Repair ID: <%= @repair.id %> Ready for Pickup
		</h4> 
	</div>
	</div>
<% else %>
	<div class="panel panel-info">
	<div class="panel-heading"> 
		<h4>
			Repair ID: <%= @repair.id %> Inactive
		</h4> 
	</div>
	</div>
<% end %>	  

<% if state == 0 %> 
	<%= link_to 'Ready for pickup', change_status_repair_path(@repair, state: 'ready_for_pickup'), method: :put, class: "btn btn-success", 
																	data: {confirm: 'Ensure that the repair description and fees are correct.'}, disabled: viewOnlyAccount? %>
	<%= link_to 'Computer was picked up', change_status_repair_path(@repair, state: 'inactive'), method: :put, class: "btn btn-info",
																				data: {confirm: 'Ensure that all accessories were also picked up.'}, disabled: viewOnlyAccount? %>
<% elsif state == 1 %>
	<%= link_to 'Computer was picked up', change_status_repair_path(@repair, :state => 'inactive'), method: :put, class: "btn btn-info",
																	  		data: {confirm: 'Ensure that all accessories were also picked up.'}, disabled: viewOnlyAccount? %>
	<%= link_to 'Make Active Again', change_status_repair_path(@repair, :state => 'active'), method: :put, class: "btn btn-danger pull-right", disabled: viewOnlyAccount? %>
<% elsif %>
	<%= link_to 'Change to "Ready for Pickup"', change_status_repair_path(@repair, :state => 'ready_for_pickup'), method: :put, class: "btn btn-success", disabled: viewOnlyAccount? %>
	<%= link_to 'Make Active Again', change_status_repair_path(@repair, :state => 'active'), method: :put, class: "btn btn-danger pull-right", disabled: viewOnlyAccount? %>
	
<% end %>

<hr>

<h4> Sales Associate: <%= @repair.sales_associate %> </h4>

<%= render 'repair_info' %>

<% if @repair.dropoff_signature_data %>
	<button id= "view_dropoff_signature_button" type="button" class="btn btn-default pull-left">View Customer Dropoff Signature</button>
	<br>
	<div id="customer_dropoff_signature" style="display: none;">
	 	<%=	@repair.dropoff_signature_data.html_safe %>
 	</div>
<%	end %>

<hr>

<p> <%= link_to 'Update Repair Info', edit_repair_path(@repair), class: "btn btn-primary" %> <p>

<h4>Technician: <%= @repair.technician %></h4>

<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Repair Description</h4></div>
      <div class="panel-body">  
        <%= simple_format(@repair.repair_description) %>
      </div>
    </div>
  </div>

	<div class="col-xs-12 col-sm-6 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Fees</h4></div>
      <div class="panel-body">  
      	Services: <%= number_to_currency(@repair.services_fee) %>
				<br>Parts: <%= number_to_currency(@repair.parts_fee) %>
      </div>
    </div>
  </div>
</div>


<%= javascript_include_tag "repairs_show" %>

app/views/repairs/unlock_new.html.erb
<% if flash[:error] %>
  <div class="row">
    <div class="col-xs-10 col-sm-6 col-md-4">
      <div class="alert alert-danger" role="alert">
        <%= flash[:error] %>  
      </div>
    </div>
  </div>
<% end %>

<%= form_tag 'unlock_new' do |f| %>
  
  <h4>Unlock Repair Request Form</h4>

  <div class="row">
    <div class="col-xs-12 col-sm-5 col-md-5">
      <%= label_tag :employee_unlock_code, 'Employee Unlock Code' %>
      <br>
      <%= password_field_tag 'employee_unlock_code' %>
      <br>
      <br>
      <%= submit_tag 'Unlock', class: "btn btn-primary"%>
    </div>
  </div>

<% end %>

<br>
<%= button_to "Unlock View Only Repair Request Form", newViewOnlyRepairForm_path, { class: "btn btn-primary" } %>