config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'newViewOnlySession' => 'sessions#newViewOnlySession'

  root 'static_pages#home'

  resources :repairs do
    member do
      put 'change_status'
    end
    collection do
      get 'unlock_new'
      post 'unlock_new'
      get 'active'
      get 'inactive'
    end
  end
  post 'newViewOnlyRepairForm' => 'repairs#newViewOnlyRepairForm'

  resources :users do
    member do
      get 'admin_edit_employee'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UCSB Computer Repair</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>

<% if logged_in? %>
<div class="container">
	<h6 class="pull-right">Logged in as: <%= current_user.first_name %> <%= current_user.last_name %></h6>
</div>
<% end %>

<div id="Application_main_container" class="container-fluid">
	<div class="row">
		<% if logged_in? %>
			<h3>
				<ul class="nav nav-pills nav-justified">
					<li> <%= link_to 'Repairs', repairs_path %> </li>
					<li> <%= link_to 'Employees', users_path %> </li>
					<li> <%= link_to 'Logout', logout_path, method: :delete %> </li>
				</ul>
			</h3>
		<% else %>
			<h3>
				<ul class="nav nav-pills nav-justified">
					<li> <%= link_to 'New Repair', new_repair_path %> </li>
					<li> <%= link_to 'Home', root_url %> </li>
					<li> <%= link_to 'Employee Login', login_path %> </li>
				</ul>
			</h3>
		<% end %>
	</div>
</div>

	<hr>

<div id="body_container" class="container">
	<body>

	<%= yield %>

	</body>
</div>
	<br>
	<br>
	<br>
	<br>


</html>